### ISSUE TITLE
github: Moving to release publish trigger for gource action

### ISSUE THREAD

**Issue by onuratakan** [Decentra-Network/Decentra-Network#487]
https://github.com/Decentra-Network/Decentra-Network/blob/47d8efffb844f6d04e6f6a598b4fb7df4ebc84e1/.github/workflows/gource.yml#L3

```  
workflow_run:
    workflows: ["Deploys"]
    types:
      - completed
```
the workflow_run section should changed to 

```  
release:
    types: [published]
```
