### ISSUE TITLE
github: Moving to release publish trigger for stability tests

### ISSUE THREAD

**Issue by onuratakan** [Decentra-Network/Decentra-Network#489]
```  
  workflow_run:
      workflows: ["Deploys"]
      types:
        - completed
```
the workflow_run section should changed to 

```  
  release:
      types: [published]
```
